---
- name: Execute task. (build_Registry_present.yml)
  include_tasks: build_Registry_present.yml
  vars:
    regedit_key: 'HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl'
    regedit_entry: 'Win32PrioritySeparation'
    regedit_value: "{{ VAR_WIN_ProcessorScheduling.Win32PrioritySeparation }}"
    regedit_type: 'REG_DWORD'
