---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_WindowsFeature is defined

- name: Execute task. (build_WindowsFeature.yml)
  import_tasks: build_WindowsFeature.yml
  when:
    - VAR_WIN_WindowsFeature is defined

