---
- name: Execute task. (build_NetAdapterConfiguration_adapter.yml)
  include_tasks: build_NetAdapterConfiguration_adapter.yml
  loop: "{{ VAR_WIN_NetAdapterConfiguration }}"
  loop_control:
    loop_var: loop_item
  when:
    - loop_item.ifDesc is defined
    - loop_item.ifDesc is not none
    - loop_item.ifDesc | length > 0
