---
- name: Execute task. (build_NetAdapterConfiguration.yml)
  include_tasks: build_NetAdapterConfiguration.yml
  when:
    - VAR_WIN_NetAdapterConfiguration is defined

- name: check param VAR_WIN_dnsSuffix_specific
  block:
    - name: check param useDomainNameDevolution
      fail:
        msg: "Parameter 'VAR_WIN_dnsSuffix_specific.useDomainNameDevolution' should be defined and must be bool type."
      when: "(VAR_WIN_dnsSuffix_specific.useDomainNameDevolution is undefined) or (VAR_WIN_dnsSuffix_specific.useDomainNameDevolution is none) or ((VAR_WIN_dnsSuffix_specific.useDomainNameDevolution != False) and (VAR_WIN_dnsSuffix_specific.useDomainNameDevolution != True))"

    - name: check param searchList
      fail:
        msg: "Parameter 'VAR_WIN_dnsSuffix_specific.searchList' cannot be NULL."
      when:
        - VAR_WIN_dnsSuffix_specific.searchList is defined
        - VAR_WIN_dnsSuffix_specific.searchList is none
  when: VAR_WIN_dnsSuffix_specific is defined

- name: set specific nds suffix
  block:
    - name: delete searchList
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: SearchList
        data:
        type: string

    - name: set UseDomainNameDevolution
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: UseDomainNameDevolution
        data: "{{ VAR_WIN_dnsSuffix_specific.useDomainNameDevolution | ternary('1','0') }}"
        type: dword

    - name: init param listTemp
      set_fact:
        listTemp: ''

    - name: set searchList
      block:
        - name: set searchList to listTemp
          set_fact:
            listTemp: "{{ [listTemp,item] | join(' ') }}"
          with_items: "{{ VAR_WIN_dnsSuffix_specific.searchList }}"

        - name: set reg SearchList
          win_regedit:
            path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
            name: SearchList
            data: "{{ listTemp | trim |replace(' ',',') }}"
            type: string
      when:
        - VAR_WIN_dnsSuffix_specific.searchList is defined
        - VAR_WIN_dnsSuffix_specific.searchList is not none

  when: VAR_WIN_dnsSuffix_specific is defined