---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_NetworkDrive is defined

- name: Execute task. (build_NetworkDrive.yml)
  import_tasks: build_NetworkDrive.yml
  when:
    - VAR_WIN_NetworkDrive is defined

