---
- name: check param VAR_WIN_ControlPanelDisplayMethod.DisplayMethod
  fail:
    msg: "The value of the parameter VAR_WIN_HardwareAutoplay.AutoplayHandlers cannot be none and the value must be a number."
  when:
    - VAR_WIN_HardwareAutoplay is defined
    - VAR_WIN_HardwareAutoplay.AutoplayHandlers is defined
    - (VAR_WIN_HardwareAutoplay.AutoplayHandlers is none) or (VAR_WIN_HardwareAutoplay.AutoplayHandlers is not number)