---
- name:  Execute task. (build_Registry_present.yml)
  include_tasks: build_Registry_present.yml
  vars:
    regedit_key: "{{ item.Key }}"
    regedit_entry: "{{ subitem.ValueName }}"
    regedit_value: "{{ subitem.Value }}"
    regedit_type: "{{ subitem.ValueType }}"
  loop: "{{ item.Values }}"
  loop_control:
    loop_var:  subitem

