---
- name: check param VAR_WIN_FeedbackAndDiagnostics.FeedbackFrequency
  fail:
    msg: "The value of the parameter VAR_WIN_FeedbackAndDiagnostics.FeedbackFrequency cannot be none and the value must be a number."
  when:
    - VAR_WIN_FeedbackAndDiagnostics.FeedbackFrequency is defined
    - (VAR_WIN_FeedbackAndDiagnostics.FeedbackFrequency is none) or (VAR_WIN_FeedbackAndDiagnostics.FeedbackFrequency is not number)

- name: check param VAR_WIN_FeedbackAndDiagnostics.AllowTelemetry
  fail:
    msg: "The value of the parameter VAR_WIN_FeedbackAndDiagnostics.AllowTelemetry cannot be none and the value must be a number."
  when:
    - VAR_WIN_FeedbackAndDiagnostics.AllowTelemetry is defined
    - (VAR_WIN_FeedbackAndDiagnostics.AllowTelemetry is none) or (VAR_WIN_FeedbackAndDiagnostics.AllowTelemetry is not number)

- name: check param VAR_WIN_FeedbackAndDiagnostics.ExperiencesAdjust
  fail:
    msg: "The value of the parameter VAR_WIN_FeedbackAndDiagnostics.ExperiencesAdjust cannot be none and the value must be a number."
  when:
    - VAR_WIN_FeedbackAndDiagnostics.ExperiencesAdjust is defined
    - (VAR_WIN_FeedbackAndDiagnostics.ExperiencesAdjust is none) or (VAR_WIN_FeedbackAndDiagnostics.ExperiencesAdjust is not number)