---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_FeedbackAndDiagnostics is defined

- name: Execute task. (build_FeedbackFrequency.yml)
  import_tasks: build_FeedbackFrequency.yml
  when:
    - VAR_WIN_FeedbackAndDiagnostics.FeedbackFrequency is defined

- name: Execute task. (build_AllowTelemetry.yml)
  import_tasks: build_AllowTelemetry.yml
  when:
    - VAR_WIN_FeedbackAndDiagnostics.AllowTelemetry is defined

- name: Execute task. (build_ExperiencesAdjust.yml)
  import_tasks: build_ExperiencesAdjust.yml
  when:
    - VAR_WIN_FeedbackAndDiagnostics.ExperiencesAdjust is defined