---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_NetFirewallRule_Inbound is defined

- name: Execute task. (build_NetFirewallRule_Inbound.yml)
  import_tasks: build_NetFirewallRule_Inbound.yml
  when:
    - VAR_WIN_NetFirewallRule_Inbound is defined

