---
- name: Execute task. (build_Registry_present.yml)
  include_tasks: build_Registry_present.yml
  vars:
    regedit_key: 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'
    regedit_entry: 'SyncDomainWithMembership'
    regedit_value: "{{ VAR_WIN_ComputerSetting.SyncDomainWithMembership }}"
    regedit_type: 'REG_DWORD'
