---
- name: Check description.
  win_shell: (Get-WmiObject -Class Win32_OperatingSystem).Description -eq "{{ VAR_WIN_ComputerSetting.Description | regex_replace('`','``') | regex_replace('"','`"') }}"
  register: check_ret
  changed_when: False

- name: Set description.
  win_shell: |
    $os = Get-wmiObject -class Win32_OperatingSystem
    $os | Set-WmiInstance -Arguments @{Description="{{ VAR_WIN_ComputerSetting.Description | regex_replace('`','``') | regex_replace('"','`"') }}"}
  when:
    - (check_ret.stdout_lines[0]) == "False"

