---
- name: Execute command. (wevtutil gl {{ item.Log }})
  win_shell: ([xml](wevtutil gl "{{ item.Log }}" /f:xml)).Channel.logging |  Select-Object 'logFileName', 'retention', 'autoBackup' | ConvertTo-Json
  register: check_ret
  changed_when: False
  check_mode: no

- name: Execute task. (build_EventLog_win_shell_item.yml)
  include_tasks: build_EventLog_win_shell_item.yml
  vars:
    check_js: "{{ check_ret.stdout | from_json }}"
