---
- name: Execute command. (wevtutil gl {{ item.Log }})
  win_shell: Get-WinEvent -ListLog "{{ item.Log }}" |  Select-Object 'MaximumSizeInBytes', 'IsClassicLog' | ConvertTo-Json
  register: check_ret
  changed_when: False
  check_mode: no

- name: Execute task. (build_EventLog_win_eventlog_item.yml)
  include_tasks: build_EventLog_win_eventlog_item.yml
  vars:
    check_js: "{{ check_ret.stdout | from_json }}"
