---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_EventLog is defined

- name: Execute task. (build_EventLog.yml)
  import_tasks: build_EventLog.yml
  when:
    - VAR_WIN_EventLog is defined

