---
- name: Execute command. (Get-WmiObject Win32_GroupUser)
  win_shell: >-
    $winhostname = hostname;
    $win_hostname = $winhostname.Replace('\r\n', '');
    Get-WmiObject Win32_GroupUser | \
    Select-Object 'GroupComponent', 'PartComponent' | \
    ForEach-Object -Begin{ \
                     $map = @{}; \
                   } \
                   -Process{ \
                     $group_component = $_.GroupComponent.Split(","); \
                     $group_domain = $group_component[0].Split("=")[1].Replace('"', ''); \
                     $group_name = $group_component[1].Split("=")[1].Replace('"', ''); \
                     $part_component = $_.PartComponent.Split(","); \
                     $user_domain = $part_component[0].Split("=")[1].Replace('"', ''); \
                     $user_name = $part_component[1].Split("=")[1].Replace('"', ''); \
                     If ($win_hostname.ToUpper() -ne $user_domain.ToUpper()) { \
                       $user_name = "$user_domain\$user_name"; \
                     } \
                     If (!$map.ContainsKey($group_domain)) { \
                       $map[$group_domain] = @{}; \
                     } \
                     If (!$map[$group_domain].ContainsKey($group_name)) { \
                       $map[$group_domain][$group_name] = @(); \
                     } \
                     $map[$group_domain][$group_name] += $user_name; \
                   } \
                   -End{$map} | \
    ConvertTo-Json
  register: result
  check_mode: no
  changed_when: false

- name: Execute task. (build_Group_item.yml)
  include_tasks: build_Group_item.yml
  vars:
    previous_items: "{{ result.stdout | from_json }}"
  loop: "{{ VAR_WIN_Group }}"
  loop_control:
    loop_var: loop_item

