---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_Group is defined

- name: Execute task. (build_Group_list.yml)
  import_tasks: build_Group_list.yml
  when:
    - VAR_WIN_Group is defined

