---
- name: set param PowerPlanSelection
  fail:
    msg: "The value of the parameter VAR_WIN_PowerOption.PowerPlanSelection cannot be none."
  when:
    - VAR_WIN_PowerOption.PowerPlanSelection is defined
    - VAR_WIN_PowerOption.PowerPlanSelection is none

- name: set param OffDisplayTime
  fail:
    msg: "The value of the parameter VAR_WIN_PowerOption.OffDisplayTime cannot be none and the value must be a number."
  when:
    - VAR_WIN_PowerOption.OffDisplayTime is defined
    - (VAR_WIN_PowerOption.OffDisplayTime is none) or (VAR_WIN_PowerOption.OffDisplayTime is not number)