---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_PowerOption is defined

- name: Execute task. (build_PowerOption.yml)
  import_tasks: build_PowerOption.yml
  when:
    - VAR_WIN_PowerOption is defined
