---
- name: Execute task. (build_Drive_info.yml)
  include_tasks: build_Drive_info.yml
  loop: "{{ VAR_WIN_PagefileSetting.Drive | default([]) }}"
  when:
    - not VAR_WIN_PagefileSetting.AutomaticManagedPagefileSetting.AutomaticManagedPagefile
