---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_ErrorReporting is defined

- name: Execute task. (build_ErrorReporting.yml)
  import_tasks: build_ErrorReporting.yml
  when:
    - VAR_WIN_ErrorReporting is defined

