---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_AutoMount is defined

- name: Execute task. (build_AutoMount.yml)
  import_tasks: build_AutoMount.yml
  when:
    - VAR_WIN_AutoMount is defined
