---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_NetIpAddress is defined

- name: Execute task. (build_NetIpAddress.yml)
  include_tasks: build_NetIpAddress.yml
  when:
    - VAR_WIN_NetIpAddress is defined
