---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_TimeZone is defined

- name: Execute task. (build_TimeZone.yml)
  import_tasks: build_TimeZone.yml
  when:
    - VAR_WIN_TimeZone is defined
