---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  vars:
    environment_level: machine
    environment_target: "{{ VAR_WIN_EnvSetting.Machine }}"
  when: VAR_WIN_EnvSetting.Machine is defined

- name: Execute task. (build_Environment.yml)
  import_tasks: build_Environment.yml
  vars:
    environment_level: machine
    environment_target: "{{ VAR_WIN_EnvSetting.Machine }}"
    environment_path: 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
  when: VAR_WIN_EnvSetting.Machine is defined

