---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_DirOption is defined

- name: Execute task. (build_DirOption.yml)
  import_tasks: build_DirOption.yml
  when:
    - VAR_WIN_DirOption is defined
