---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_GroupPolicy is defined

- name: Execute task. (build_GroupPolicy.yml)
  import_tasks: build_GroupPolicy.yml
  when:
    - VAR_WIN_GroupPolicy is defined

