---
- name: set OwnerAndOrganization32.RegisteredOrganization
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion
    name: RegisteredOrganization
    data: "{{ VAR_WIN_OwnerAndOrganization.OwnerAndOrganization32.RegisteredOrganization }}"
    type: string
  when:
    - VAR_WIN_OwnerAndOrganization.OwnerAndOrganization32.RegisteredOrganization is defined

- name: set OwnerAndOrganization32.RegisteredOwner
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion
    name: RegisteredOwner
    data: "{{ VAR_WIN_OwnerAndOrganization.OwnerAndOrganization32.RegisteredOwner }}"
    type: string
  when:
    - VAR_WIN_OwnerAndOrganization.OwnerAndOrganization32.RegisteredOwner is defined