---
- name: set OwnerAndOrganization64.RegisteredOrganization
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    name: RegisteredOrganization
    data: "{{ VAR_WIN_OwnerAndOrganization.OwnerAndOrganization64.RegisteredOrganization }}"
    type: string
  when:
    - VAR_WIN_OwnerAndOrganization.OwnerAndOrganization64.RegisteredOrganization is defined

- name: set OwnerAndOrganization64.RegisteredOwner
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    name: RegisteredOwner
    data: "{{ VAR_WIN_OwnerAndOrganization.OwnerAndOrganization64.RegisteredOwner }}"
    type: string
  when:
    - VAR_WIN_OwnerAndOrganization.OwnerAndOrganization64.RegisteredOwner is defined