---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_OwnerAndOrganization is defined

- name: Execute task. (build_OwnerAndOrganization32.yml)
  import_tasks: build_OwnerAndOrganization32.yml
  when:
    - VAR_WIN_OwnerAndOrganization.OwnerAndOrganization32 is defined

- name: Execute task. (build_OwnerAndOrganization64.yml)
  import_tasks: build_OwnerAndOrganization64.yml
  when:
    - VAR_WIN_OwnerAndOrganization.OwnerAndOrganization64 is defined