---
- name: Execute task. (check.yml)
  include_tasks: check.yml
  when:
    - VAR_WIN_SNP is defined

- name: Execute task. (build_SNP.yml)
  import_tasks: build_SNP.yml
  when:
    - VAR_WIN_SNP is defined
